const appname = "Metbuy_seller",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password",
    anyProblem = "In case of any difficulty, contact admin or",
    contact = "creategen@solution4u.com",
    emailHint = "eg. vender@metbuy.in",
    passHint = "* * * * * *",
    dashboard = "DashBoard",
    rating = "Rating",
    totalSales = "Total Sales",
    popular = "Popular Products",
    orders = "Orders",
    unpaid = "Unpaid",
    paid = "Paid",
    products = "Products",
    settings = "Settings",
    shopSettings = "Shop Settings",
    messages = "Messages",
    logout = "Logout",
    credit = "@samarthmishra",
    uname = "Username",
    conpass = "Confirm Password",
    shops ="Shop Settings",
    address ="Address",
    chat = "Chats";

//Shop Setting strings

const nameHint = "eg.vendor Name",
    shopDescHint = "Enter your shop description",
    shopMobileHint = "eg. +7894561230",
    shopAddressHint = "eg. near kanpur metro station",
    description = "Description",
    mobile = "Shop Mobile",
    website = "Shop Website",
    name = "Seller name",
    featured = "Featured",
    edit = "Edit",
    remove = "Remove",
    save = "Save",
    editscreen = "Edit Profile",
    changeImage = "Change Image",
    loggedin = "Login Successfully";

